### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

### ISSUE THREAD

**Issue by tohenryliu** [contentful/contentful.py#20]
from this code:
import contentful
import logging

logging.basicConfig(level=logging.DEBUG)

client = contentful.Client(...)

entries = client.entries()
sync = client.sync({'initial': True})

Stacktrace:
DEBUG:urllib3.connectionpool:https://cdn.contentful.com:443 "GET /spaces/wsn2eby0by7h/sync?initial=true HTTP/1.1" 200 57767
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/contentful/client.py", line 314, in sync
    query
  File "/usr/local/lib/python3.6/site-packages/contentful/client.py", line 533, in _get
    max_depth=self.max_include_resolution_depth
  File "/usr/local/lib/python3.6/site-packages/contentful/resource_builder.py", line 51, in build
    return self._build_array()
  File "/usr/local/lib/python3.6/site-packages/contentful/resource_builder.py", line 65, in _build_array
    ) for item in self.json['items']]
  File "/usr/local/lib/python3.6/site-packages/contentful/resource_builder.py", line 65, in <listcomp>
    ) for item in self.json['items']]
  File "/usr/local/lib/python3.6/site-packages/contentful/resource_builder.py", line 87, in _build_item
    max_depth=self.max_depth
  File "/usr/local/lib/python3.6/site-packages/contentful/resource.py", line 84, in __init__
    self._fields = self._hydrate_fields(item, localized, includes)
  File "/usr/local/lib/python3.6/site-packages/contentful/resource.py", line 112, in _hydrate_fields
    includes
  File "/usr/local/lib/python3.6/site-packages/contentful/entry.py", line 50, in _coerce
    return content_type_field.coerce(value)
  File "/usr/local/lib/python3.6/site-packages/contentful/content_type_field.py", line 39, in coerce
    return self._coercion.coerce(value)
  File "/usr/local/lib/python3.6/site-packages/contentful/content_type_field_types.py", line 62, in coerce
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

**Comment by dlitvakb** [comment]
Hi @tohenryliu,

Which version of the library are you using? Could you provide me the bit of the JSON response that may be causing this?

Cheers

**Comment by tohenryliu** [comment]
Hi @dlitvakb,

contentful==1.3.0

I have been using raw_mode for past few days, that worked fine.
Now I'm trying to switch back to try to reproduce the problem. I'm not able to do so. 
I get an Array back instead of SyncPage when I call it. 
I guess this code failed to detect it's a sync repsonse
https://github.com/contentful/contentful.py/blob/master/contentful/resource_builder.py#L45

any idea?
what info can I provide to help you investigate, or spaceId?

thanks

**Comment by tohenryliu** [comment]
looks like this fix is not released yet. 
https://github.com/contentful/contentful.py/commit/ba96ff695651471139ff79c1ff42cbb5952281fb#diff-76b6db7d0d6479dcbbd32a9cce661f55

**Comment by dlitvakb** [comment]
Hey @tohenryliu,

I'll look into making a release within this week.

Cheers

**Comment by dlitvakb** [comment]
This has been now released in `v1.4.1`

Please let me know if you continue with issues after the upgrade.

Cheers

**Comment by paribaker** [comment]
This bug still seems to be affecting some code, when I retrieve a field with a decimal value it is coerced to an integer. 
when switching over to a text field and taking a decimal input a value error occurs 

`
special variables
function variables
'fundTitle':'New Second Fund'
'rightUsageValue':200
'leftUsageValue':20.54
len():3
len():3
res.fields()
{'fund_title': 'New Second Fund', 'right_usage_value': 200, 'left_usage_value': 20}
special variables
function variables
'fund_title':'New Second Fund'
'right_usage_value':200
'left_usage_value':20
`
The top leftUsageFund from the raw response is a decimal whereas in the formatted version it is coerced into an integer

`
ValueError at /api/contentful/funds/
invalid literal for int() with base 10: '2.10'
`
