### ISSUE TITLE
python 3.8 support?

### ISSUE THREAD

**Issue by ekimia** [contentful/contentful.py#66]
Unsure if its related to 3.8, but getting this error when importing contentful:

```
In [1]: import contentful
Traceback (most recent call last):

  File "/Users/ek/.pyenv/versions/3.8.0/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-1391c0406839>", line 1, in <module>
    import contentful

  File "/Users/ek/.pyenv/versions/3.8.0/lib/python3.8/site-packages/contentful/__init__.py", line 1, in <module>
    from .client import Client  # noqa: F401

  File "/Users/ek/.pyenv/versions/3.8.0/lib/python3.8/site-packages/contentful/client.py", line 7, in <module>
    from .resource_builder import ResourceBuilder

  File "/Users/ek/.pyenv/versions/3.8.0/lib/python3.8/site-packages/contentful/resource_builder.py", line 2, in <module>
    from .entry import Entry

  File "/Users/ek/.pyenv/versions/3.8.0/lib/python3.8/site-packages/contentful/entry.py", line 1, in <module>
    from .resource import FieldsResource

  File "/Users/ek/.pyenv/versions/3.8.0/lib/python3.8/site-packages/contentful/resource.py", line 1, in <module>
    import dateutil.parser

  File "/Users/ek/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax
```

**Comment by sman591** [comment]
Python 3.8 is included in CI, so I wonder if this is something else: https://github.com/contentful/contentful.py/blob/32594aa6ff40d208e7eed2d0b1c0ad8edb19a6e0/.travis.yml#L8

**Comment by rubydog** [comment]
@sman591 are you still facing the issue?

**Comment by sman591** [comment]
No, sorry! This can be closed
